# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kamil <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/23 21:09:39 by kamil             #+#    #+#              #
#    Updated: 2024/09/23 21:09:41 by kamil            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Las Flags para compilar
FLAG = -Wall -Wextra -Werror
# El nombre del "Programa"
NAME = libft.a
# Los Archivos "librerias" .c
SRC = ft_isalpha.c \
		ft_isdigit.c \
		ft_isalnum.c \
		ft_isascii.c \
		ft_isprint.c \
		ft_strlen.c \
		ft_strlcpy.c \
		ft_strlcat.c \
		ft_strncmp.c \
		ft_atoi.c \
		ft_tolower.c \
		ft_toupper.c \
		ft_memset.c \
		ft_bzero.c \
		ft_memmove.c \
		ft_memcpy.c \
		ft_strnstr.c \
		ft_strchr.c \
		ft_strrchr.c \
		ft_memchr.c \
		ft_memcmp.c \
		ft_calloc.c \
		ft_strdup.c \
		ft_substr.c \
		ft_strjoin.c \
		ft_strtrim.c \
		ft_putchar_fd.c \
		ft_putstr_fd.c \
		ft_putendl_fd.c \
		ft_putnbr_fd.c \
		ft_strmapi.c \
		ft_split.c \
		ft_itoa.c \
		ft_striteri.c \
	  
# Los Archivos "librerias" .o
OBJ = $(SRC:.c=.o)
# Los archivos "librerias" .c de Bonus
BONUS = ft_lstnew_bonus.c \
		ft_lstadd_front_bonus.c \
		ft_lstsize_bonus.c \
		ft_lstlast_bonus.c \
		ft_lstadd_back_bonus.c \
		ft_lstdelone_bonus.c \
		ft_lstclear_bonus.c \
		ft_lstiter_bonus.c \
		ft_lstmap_bonus.c \
# Los Archivos "librerias" .o de Bonus
BONUS_OBJ = $(BONUS:.c=.o)
# Se refiere a lo ejecutable
all: $(NAME)
# Creo el "Programa" a partir de los archivos .o
$(NAME): $(OBJ)
	@ar rcs $(NAME) $(OBJ)
	@echo "$(NAME) created and indexed"
# Creo los archivos .o
%.o: %.c
	@gcc $(FLAG) -c $< -o $@
# Borra los archivos .o
clean:
	@rm -f $(OBJ) $(BONUS_OBJ)
	@echo "OBJ cleaned"
# Borra los archivos .o y el "Programa"
fclean: clean
	@rm -f $(OBJ) $(BONUS_OBJ)
	@rm -f $(NAME)
	@echo "All objects and executable cleaned"
# Borra el "Programa" y recompila
re: fclean all
# Compila el "Programa" con los objetos de Bonus
bonus: $(BONUS_OBJ) $(OBJ)
	@ar rcs $(NAME) $(OBJ) $(BONUS_OBJ)
	@echo "$(NAME) created and indexed with bonus"
# Indica a Make que no son archivos reales, sino nombres de objetivos, Esto evita conflictos si existieran archivos con esos mismos nombres.
.PHONY:	all clean fclean re bonus
